wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.10.12
    cli_version: 0.17.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1721912114
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 23
      - 37
      4: 3.10.12
      5: 0.17.5
      8:
      - 5
      13: linux-x86_64
cascade:
  desc: null
  value: 12
chans:
  desc: null
  value: 9
sens_chans:
  desc: null
  value: 5
